services:
  email-classification: 
    build:
      context: .
      dockerfile: ./src/EmailClassification.API/Dockerfile
    image: ${EMAIL_API_IMAGE}
    container_name: ${EMAIL_API_CONTAINER}
    ports:  
      - "{BACKEND_PORT}:8080"
    depends_on:
      - postgres
      - elastic
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};UserId=${DB_USER};Password=${DB_PASSWORD};
      - Elastic__Url=${ELASTIC_URL}
      - Elastic__Index=${ELASTIC_INDEX}
    networks:
      - emailcf

  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - emailcf

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: ${ELASTICSEARCH_CONTAINER}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "{ELASTIC_PORT}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - emailcf

volumes:
  postgresdata:
    driver: local
  esdata:
    driver: local

networks:
  emailcf:
    driver: bridge
  
